<?
$PERM["portfolio"]["2"]="D";
$PERM["portfolio"]["3"]="D";
$PERM["portfolio"]["4"]="D";
$PERM["portfolio"]["7"]="D";
$PERM["portfolio"]["6"]="D";
$PERM["portfolio"]["5"]="D";
$PERM["portfolio"]["*"]="D";
$PERM["statistic_na"]["2"]="D";
$PERM["statistic_na"]["3"]="D";
$PERM["statistic_na"]["4"]="D";
$PERM["statistic_na"]["7"]="R";
$PERM["statistic_na"]["6"]="D";
$PERM["statistic_na"]["5"]="D";
$PERM["statistic_na"]["*"]="D";
$PERM["/"]["*"]="R";
$PERM["about"]["6"]="X";
$PERM["about"]["5"]="X";
$PERM["search"]["5"]="W";
$PERM["products"]["5"]="W";
$PERM["services"]["5"]="W";
$PERM["news"]["5"]="W";
$PERM["contacts"]["5"]="W";
$PERM["company"]["5"]="W";
$PERM["index.php"]["5"]="W";
?>